# config option we are interested in

individuals:
- mouseA
- mouseB
multianimalbodyparts:
- a
- b
- c
- d
- e

skeleton:
- - a
  - b
- - b
  - c
- - c
  - d
- - d
  - e
  
numframes2pick: 80
pcutoff: 0.1
dotsize: 3
colormap: rainbow

TrainingFraction:
- 0.80
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
snapshotindex: all
batch_size: 32
