Task: CaliforniaMouse
scorer: Marler
# date: 
multianimalproject: true
identity: false

project_path: ~/CaliforniaMouse-Marler

# should have 10 videos
video_sets:
  # C:\Users\marle\Desktop\Yoo Sung Jang\pilot-4-yoosung-2022-02-25\videos\ANMR0001-low.mp4:
  #   crop: 0, 480, 0, 270

individuals:
- mouseA
- mouseB
uniquebodyparts: []
multianimalbodyparts:
- bodypart1
- bodypart2
- bodypart3
skeleton:
- - bodypart1
  - bodypart2
- - bodypart2
  - bodypart3
- - bodypart1
  - bodypart3
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 20

skeleton_color: black
# pcutoff possibly lower
pcutoff: 0.6
dotsize: 3
alphavalue: 0.7
colormap: rainbow

TrainingFraction:
- 0.80
# iteration will increment automatically
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
# snapshats to evaluate on
snapshotindex: all
# might have to reduce batch_size depends on GPU situation
batch_size: 32

cropping: false
