# config option we are interested in

individuals:
- mouseA
- mouseB
multianimalbodyparts:
- nose
- left_ear
- right_ear
- tail_base

skeleton:
- - nose
  - left_ear
- - nose
  - right_ear
- - left_ear
  - right_ear
- - left_ear
  - tail_base
- - right_ear
  - tail_base
  
  
numframes2pick: 20
pcutoff: 0.6
dotsize: 3
colormap: rainbow

TrainingFraction:
- 0.80
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
snapshotindex: all
batch_size: 32
