# config option we are interested in

individuals:
- mouseA
- mouseB
multianimalbodyparts:
- 1
- 2
- 3
- 4
- 5

skeleton:
- - 1
  - 2
- - 2
  - 3
- - 3
  - 4
- - 4
  - 5
  
numframes2pick: 250
pcutoff: 0.1
dotsize: 3
colormap: rainbow

TrainingFraction:
- 0.80
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
snapshotindex: all
batch_size: 32
